openapi: 3.0.0
info:
  description: "Need a helping hand to manage your books 😺? Well, you're in luck! This API will let you manage your books with ease! 😻"
  version: "0.1.0"
  title: "📖 Minimalist Book Manager API"
schemes:
- "https"
- "http"
paths:
  /api/v1/books:
    get:
      summary: "Get all books"
      responses:
        "200":
          description: "An array of books"
    post:
      summary: "Add a new book"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/Book'
      responses:
        "201":
          description: "Created"
          schema:
            $ref: "#/definitions/Book"
  /api/v1/books/{bookId}:
    get:
      summary: "Get a single book by bookId"
      produces:
      - "application/json"
      parameters:
      - name: "bookId"
        in: "path"
        description: "Numeric ID of the book to get"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "A single book"
          schema:
            $ref: "#/definitions/Book"

definitions:
  Book:
        type: object
        required:
          - title
          - author
        properties:
          bookId:
            type: integer
            description: Auto-generated book id
          title:
            type: string
            description: Book title
          author:
            type: string
            description: Book author